export default {
  'primary-color': '#703beb',
  'success-color': '#6226e9',
  'info-color': '#601dff',
  'warning-color': '#ffba34',
  'error-color': '#f15f57',
  'highlight-color': '#fd563d',
  'body-background': '#ffffff',
  'component-background': '#ffffff',
  'icon-color-hover': '#252441',
  'heading-color': '#4c4c6f',
  'text-color': '#49495d',
  'text-color-secondary': '#7f7e94',
  'border-color-base': '#dadae2',
  'border-color-split': '#f5f5fa',
  'layout-body-background': '#f8f8f8',
  'layout-header-background': '#363255',
  'border-radius-base': '4px',
  'border-radius-sm': '4px',
  'shadow-color': '#e2e2e2',
};
